### ISSUE TITLE
Before we run the examples, wechaty should be installed.

### ISSUE THREAD

**Issue by kaffa** [Chatie/wechaty-getting-started#41]
Wechaty installation is not so easy that it tooks me 4 hours to complete this *simple* task in Windows 10 Home Edition.

First, there're 2 ways to install wechaty, one is npm, the other is docker. Because docker needs at least Windows Proffesional to run in, we only have the first choice if we bought a home-use Windows and are not going to get the Windows Pro at $99.

Secondly, if we choose install it via npm way, some requirements and descriptions missed in the installation docs:
1. node, the version needs 10 or above
2. Python 2.7, [node-gyp](https://www.npmjs.com/package/node-gyp) needs it
3. Microsoft's windows-build-tools, node-gyp needs it, so Visual Studio Community is a nice choice.
4. [puppeteer](https://github.com/GoogleChrome/puppeteer), the package is hard to download if we don't use cnpm

If we complete the 4 steps, wechaty runs!

Then, the QRCode in Windows Cmd Prompt is in a mess, I have to copy it from console to notepad and change the font setting to "Lucida Console", font-size 5, CTRL+A to reverse the color of the QRCode.

Finally, after I scaned it, the ding-dong-bot run, I sent a ding, it replied a dong. That was the story yestorday.

**Comment by zixia** [comment]
@kaffa Thanks for summary this for Windows developers!

Would you like to share your experience on our Chatie Blog as a _Windows User Tutorial_? Because what you write will be very valuable for the community.

If you agree, I'll send you a invitition on our Blog Repo. And I also noticed that you had published a blog about this on your Blog in Chinese, you can link back to your blog after you finished the Chatie Blog.

**Comment by kaffa** [comment]
Thanks! I would like to do that.

**Comment by zixia** [comment]
Close this issue because @kaffa had published his blog post at <https://blog.chatie.io/wechaty-installation-in-windows-10/>
